blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<slug:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<slug:slug>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing import views
from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('newsletters', views.NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletter/<int:pk>/', views.NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletter/create/', views.NewsletterCreateView.as_view(), name='newsletter_create'),
    path('newsletter/<int:pk>/update/', views.NewsletterUpdateView.as_view(), name='newsletter_update'),
    path('newsletter/<int:pk>/delete/', views.NewsletterDeleteView.as_view(), name='newsletter_delete'),

    path('messages', views.MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', views.MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', views.MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', views.MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', views.MessageDeleteView.as_view(), name='message_delete'),

    path('clients', views.ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', views.ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', views.ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),

    path('attempts', views.AttemptListView.as_view(), name='attempt_list'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password-reset/', UserPasswordReset.as_view(), name='password_reset'),
    path('password-done/', UserPasswordDone.as_view(), name='password_done'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
]

mailing/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    name = models.CharField(max_length=100, verbose_name='Ф.И.О.')
    email = models.EmailField(unique=True, verbose_name='почта')
    comment = models.TextField(verbose_name='комментарий')

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.name}: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Newsletter(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название рассылки', null=True, blank=True, default='Рассылка')
    start_date = models.DateTimeField(verbose_name='дата и время начала рассылки')
    end_date = models.DateTimeField(verbose_name='дата и время окончанмя рассылки', null=True, blank=True)
    periodicity = models.CharField(max_length=100, verbose_name='периодичность', default='Ежедневно',
                                   choices=(('Ежедневно', 'Ежедневно'),
                                            ('Еженедельно', 'Еженедельно'),
                                            ('Ежемесячно', 'Ежемесячно')))
    status = models.CharField(max_length=100, verbose_name='статус', default='Создана',
                              choices=(('Создана', 'Создана'),
                                       ('Запущена', 'Запущена'),
                                       ('Завершена', 'Завершена')))

    clients = models.ManyToManyField(Client, blank=True, related_name='clients', verbose_name='Клиенты')
    message = models.OneToOneField('Message', on_delete=models.SET_NULL, blank=True, null=True,
                                   related_name='message', verbose_name='Сообщение')

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('can_disable_newsletter', 'Can disable newsletter')
        ]


class Message(models.Model):
    subject = models.CharField(max_length=100, verbose_name='тема письма')
    text = models.TextField(verbose_name='текст письма')

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.subject}: {self.text}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Attempt(models.Model):
    at_date = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    is_success = models.BooleanField(default=False, verbose_name='успешность попытки')
    server_response = models.TextField(default=False, verbose_name='ответ сервера')
    newsletter = models.ForeignKey(Newsletter, on_delete=models.CASCADE, related_name='newsletter')

    def __str__(self):
        return f'{self.at_date}: {self.is_success}'

    class Meta:
        verbose_name = 'Попытка'
        verbose_name_plural = 'Попытки'

mailing/forms.py
from django import forms

from mailing.models import Client, Newsletter, Message


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = ['name', 'start_date', 'end_date', 'periodicity', 'clients', 'message', 'status']

    def __init__(self, *args, **kwargs):
        """Переопределяет поля(клиенты, сообщение) с учетом фильтрации по пользователю"""
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)


class StatusNewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = ('name', 'status',)

    def __init__(self, *args, **kwargs):
        """Удаляем лишний словарь, он нужен для другой формы"""
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mailing.forms import NewsletterForm, StatusNewsletterForm
from mailing.mixins import UserAutofillMixin, OwnerMixin, OwnerManagerMixin, KwargsMixin, NotManagerMixin
from mailing.models import Newsletter, Message, Client, Attempt
from mailing.services import get_three_articles, get_newsletters


def home_page(request):
    """Главная страница"""
    data = {'newsletters': '', 'active_newsletters': '', 'clients': '', 'blog': []}

    data['newsletters'], data['active_newsletters'], data['clients'] = get_newsletters(request, data)

    data['blog'] = get_three_articles(data)

    return render(request, 'mailing/home_page.html', data)


class NewsletterListView(LoginRequiredMixin, ListView):
    model = Newsletter
    ordering = 'user'


class NewsletterDetailView(LoginRequiredMixin, OwnerManagerMixin, DetailView):
    model = Newsletter


class NewsletterCreateView(LoginRequiredMixin, NotManagerMixin, UserAutofillMixin, KwargsMixin, CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy('mailing:newsletter_list')


class NewsletterUpdateView(LoginRequiredMixin, OwnerManagerMixin, KwargsMixin, UpdateView):
    model = Newsletter
    form_class = NewsletterForm

    # fields = ['start_date', 'end_date', 'periodicity', 'clients', 'message', 'status']

    def get_success_url(self):
        return reverse('mailing:newsletter_detail', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return NewsletterForm
        if user.has_perms(['mailing.can_disable_newsletter', 'users.can_disable_user']):
            return StatusNewsletterForm
        raise PermissionDenied


class NewsletterDeleteView(LoginRequiredMixin, OwnerMixin, DeleteView):
    model = Newsletter
    success_url = reverse_lazy('mailing:newsletter_list')


class MessageListView(LoginRequiredMixin, ListView):
    model = Message


class MessageDetailView(LoginRequiredMixin, OwnerMixin, DetailView):
    model = Message


class MessageCreateView(LoginRequiredMixin, NotManagerMixin, UserAutofillMixin, CreateView):
    model = Message
    fields = ['subject', 'text']
    success_url = reverse_lazy('mailing:message_list')


class MessageUpdateView(LoginRequiredMixin, OwnerMixin, UpdateView):
    model = Message
    fields = ['subject', 'text']

    def get_success_url(self):
        return reverse('mailing:message_detail', args=[self.kwargs.get('pk')])


class MessageDeleteView(LoginRequiredMixin, OwnerMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client


class ClientDetailView(LoginRequiredMixin, OwnerMixin, DetailView):
    model = Client


class ClientCreateView(LoginRequiredMixin, NotManagerMixin, UserAutofillMixin, CreateView):
    model = Client
    fields = ['name', 'email', 'comment']
    success_url = reverse_lazy('mailing:client_list')


class ClientUpdateView(LoginRequiredMixin, OwnerMixin, UpdateView):
    model = Client
    fields = ['name', 'email', 'comment']

    def get_success_url(self):
        return reverse('mailing:client_detail', args=[self.kwargs.get('pk')])


class ClientDeleteView(LoginRequiredMixin, OwnerMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')


class AttemptListView(LoginRequiredMixin, ListView):
    model = Attempt

mailing/templates/mailing/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Цифровой мир</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'mailing/includes/inc_menu.html' %}
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Сервис рассылки</h1>
                {% if user.is_authenticated %}
                <p class="lead text-body-secondary"></p>
                {% if not perms.mailing.can_disable_newsletter and not perms.users.can_disable_user %}
                <a href="{% url 'mailing:newsletter_create' %}" class="btn btn-primary my-2">Создать рассылку</a>
                <a href="{% url 'mailing:message_create' %}" class="btn btn-primary my-2">Создать сообщение</a>
                <a href="{% url 'mailing:client_create' %}" class="btn btn-primary my-2">Создать клиента</a>
                {% endif %}
                {% else %}
                <h2 class="fw-light">Зарегистрируйтесь и создайте первую рассылку</h2>
                <p>
                    <a href="{% url 'users:register' %}" class="text-primary">Регистрация</a>
                </p>
                <p>
                    <a href="{% url 'users:login' %}" class="text-primary">Вход</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>

    {% block content %}
    {% endblock %}

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="col">
                    <p class="card-text">Действительно хотите удалить: {{ object.name }}</p>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a href="{% url 'mailing:client_list' %}" class="btn btn-secondary">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            {% if user == object.user %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p class="card-text">{{ object.email }}</p>
                        <p class="card-text">{{ object.comment }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailing:client_detail' object.pk %}" role="button">Посмотреть</a>
                                <a class="btn btn-secondary" href="{% url 'mailing:client_update' object.pk %}" role="button">Изменить</a>
                                <a class="btn btn-danger" href="{% url 'mailing:client_delete' object.pk %}" role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/home_page.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
{% if perms.mailing.can_disable_newsletter and perms.users.can_disable_user %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <h1><a href="{% url 'users:user_list' %}" class="text-primary">Пользователи</a></h1>
            <h1><a href="{% url 'mailing:newsletter_list' %}" class="text-primary">Рассылки</a></h1>
        </div>
    </div>
</div>
{% else %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card-body">
                    <h2 class="card-text">{{ newsletters }}</h2>
                </div>
            </div>
            <div class="col">
                <div class="card-body">
                    <h2 class="card-text">{{ active_newsletters }}</h2>
                </div>
            </div>
            <div class="col">
                <div class="card-body">
                    <h2 class="card-text">{{ clients }}</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for obj in blog %}
            <div class="col">
                <div class="card-body">
                    {% if obj.image %}
                    <img src="{{ obj.image | media_filter }}">
                    {% endif %}
                    <h2 class="card-text">{{ obj.title }}</h2>
                    <h3 class="card-text">{{ obj.content | truncatewords:50 }}</h3>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            {% if user == object.user %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.subject }}</p>
                        <p class="card-text">{{ object.text }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailing:message_detail' object.pk %}"
                                   role="button">Посмотреть</a>
                                <a class="btn btn-secondary" href="{% url 'mailing:message_update' object.pk %}"
                                   role="button">Изменить</a>
                                <a class="btn btn-danger" href="{% url 'mailing:message_delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/newsletter_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            {% if user == object.user or perms.mailing.can_disable_newsletter %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p class="card-text">{{ object.start_date }}</p>
                        <p class="card-text">{{ object.end_date }}</p>
                        <p class="card-text">{{ object.periodicity }}</p>
                        <p class="card-text">{{ object.status }}</p>
                        {% if perms.mailing.can_disable_newsletter %}
                        <p class="card-text">{{ object.user }}</p>
                        {% endif %}
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailing:newsletter_detail' object.pk %}"
                                   role="button">Посмотреть</a>
                                <a class="btn btn-secondary" href="{% url 'mailing:newsletter_update' object.pk %}"
                                   role="button">Изменить</a>
                                {% if user == object.user %}
                                <a class="btn btn-danger" href="{% url 'mailing:newsletter_delete' object.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}