blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<slug:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<slug:slug>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing import views
from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('newsletters', views.NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletter/<int:pk>/', views.NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletter/create/', views.NewsletterCreateView.as_view(), name='newsletter_create'),
    path('newsletter/<int:pk>/update/', views.NewsletterUpdateView.as_view(), name='newsletter_update'),
    path('newsletter/<int:pk>/delete/', views.NewsletterDeleteView.as_view(), name='newsletter_delete'),

    path('messages', views.MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', views.MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', views.MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', views.MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', views.MessageDeleteView.as_view(), name='message_delete'),

    path('clients', views.ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', views.ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', views.ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),

    path('attempts', views.AttemptListView.as_view(), name='attempt_list'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password-reset/', UserPasswordReset.as_view(), name='password_reset'),
    path('password-done/', UserPasswordDone.as_view(), name='password_done'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='Аватар', blank=True, null=True,
                               help_text='Загрузите изображение')
    phone = PhoneNumberField(verbose_name='Телефон', blank=True, null=True, help_text='Введите номер телефона')
    country = models.CharField(verbose_name='Страна', blank=True, null=True, help_text='Введите страну')

    token = models.CharField(max_length=100, verbose_name='токен', blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('can_disable_user', 'Can disable user')
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from users.mixins import StyleFormMixin


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'password')


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'avatar', 'phone', 'country',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserPasswordResetForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['email']

users/views.py
import secrets

from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView, ListView

from users.forms import UserLoginForm, UserRegisterForm, UserProfileForm, UserPasswordResetForm
from users.mixins import ManagerMixin
from users.models import User
from users.services import send_verification_by_email, restore_password


class UserLogin(LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_verification_by_email(user, url)
        return super().form_valid(form)


def email_verification(request, token):
    """Верифицирует пользователя, если токен совпадает"""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordReset(TemplateView):
    template_name = 'users/password_reset.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = UserPasswordResetForm()
        context['form'] = form

        return context

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        email = request.POST.get('email')
        context['email'] = email

        password = secrets.token_urlsafe(8)
        message = f'Здравствуйте! Вы запрашивали новый пароль. Ваш новый пароль: {password}'

        user = User.objects.get(email=email)
        user.password = make_password(password)
        user.save()
        restore_password(message, email)

        return render(request, 'users/password_done.html', context)


class UserPasswordDone(TemplateView):
    template_name = 'users/password_done.html'


class UserListView(LoginRequiredMixin, ManagerMixin, ListView):
    model = User


class UserUpdateView(LoginRequiredMixin, ManagerMixin, UpdateView):
    model = User
    fields = ('is_active',)
    template_name = 'users/user_update.html'
    success_url = reverse_lazy('users:user_list')

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <p>
                        <a href="{% url 'users:password_reset' %}" class="btn btn-secondary">Восстановить пароль</a>
                    </p>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_done.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col">
                    Ваш новый пароль был выслан на вашу почту: {{ email }}
                </div>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Войти в систему</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col">
                    {% csrf_token %}
                    Введите адрес электронной почты:
                    {{ form.email }}
                    <button type="submit" class="btn btn-primary">Восстановить пароль</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if user.is_authenticated %}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    <a href="{% url 'mailing:home_page' %}" class="btn btn-secondary">Отмена</a>
                    {% else %}
                    <button type="submit" class="btn btn-primary">Зарегистрировать</button>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        {% if object.avatar %}
                        <img src="{{ object.avatar | media_filter }}">
                        {% endif %}
                        <p class="card-text">{{ object.email }}</p>
                        <p class="card-text">{{ object.phone }}</p>
                        <p class="card-text">{{ object.country }}</p>
                        <p class="card-text">{{ object.is_active }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-secondary" href="{% url 'users:user_update' object.pk %}"
                                   role="button">Изменить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_update.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col">
                    {% csrf_token %}
                    {% if object.avatar %}
                    <img src="{{ object.avatar | media_filter }}">
                    {% endif %}
                    Изменить статус ползователя:
                    {{ user }}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    <a href="{% url 'users:user_list' %}" class="btn btn-secondary">Отмена</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}